apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-migration-job"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    # Defines a weight for a hook which will help build a deterministic executing order
    "helm.sh/hook-weight": "4"
    # Delete the previous resource before a new hook is launched (default)
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  # The back-off limit is set by default to 6
  backoffLimit: 2
  template:
    metadata:
      name: "{{ .Release.Name }}-migration-job"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox
          args:
            - "exit 1"