repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: prometheus
    namespace: prometheus-no-rbac
    chart: prometheus/prometheus
    set:
      - name: rbac.create
        value: false